### ISSUE TITLE
Button text is too low on the baseline in Firefox

### ISSUE THREAD

**Issue by Shakyamuni177te** [hoegrammer/democracy#12]
Issue raised on behalf of Aaron Gray. Assuming Linux is runtime environment.

**Comment by AaronNGray** [comment]
The baseline of the "Add Proposal" text in the Button is lower in FireFox than in other browsers. I did not mean this to become an issue. Its just a minor annoyance, but looks crappy. Theres probably a work around but finding it maybe fun.

**Comment by AaronNGray** [comment]
BTW Gray is spelt with an A Peter !

**Comment by Shakyamuni177te** [comment]
I need to attend the demo.

Will look into this later just to keep you happy Aaron GrAy :p.

**Comment by Shakyamuni177te** [comment]
Fixed as of current builds in Firefox 38.0, on Ubuntu 12.04 (281580) (64-bit).
