### ISSUE TITLE
Drywall

### ISSUE THREAD

**Issue by Shakyamuni177te** [hoegrammer/democracy#20]
Aaron is keen to examine using drywall. Is this a usable solution at this time?

**Comment by hoegrammer** [comment]
It's worth him having a look

**Comment by AaronNGray** [comment]
The one in my repo https://github.com/AaronNGray/drywall thats a fork of the original actually works and I have added a line that sets the root password up in the README.md.

**Comment by Shakyamuni177te** [comment]
Excellent. Issue closed.

**Comment by AaronNGray** [comment]
Basically we can use it a a vehicle for the prototype, but for the actual version we want our own frameworks for the servers. Drywall uses Jade for its templates which I am not keen on and would rather swap it over to Underscore templates at some point maybe.

**Comment by Shakyamuni177te** [comment]
:+1:

**Comment by hoegrammer** [comment]
If you don't want to use it for the real thing, then let's not use it for the prototype either. It's a very opinionated framework so we would have to do the prototype "it's way". That would be a waste of time if we are not using it for the real thing.

**Comment by hoegrammer** [comment]
I want to check we are all on the same page here since @Shakyamuni177te and I have agreed that the prototype does not need actual user account validation and will just have a mock-up login.

**Comment by Shakyamuni177te** [comment]
Yeah. I've kept my head down on this one so far but as far as I'm concerned we need to be realistic about what can be achieved in time for the deadline. To me the most important thing is to get something useful finished in time for that.

I can understand where you're coming from regarding the prototype Aaron, but I think it sends a strong message if we have a functional prototype in time for the demonstration, even if DemocracyOS ends up being used in the initial showcase (note to Naomi in case I didn't explain: we were intending to port DemocracyOS initially as it has name-recognition and a full support-base but now we're join likely to take the name and the odd feature here and there).

I think what's best is if tomorrow we make sure we setup IRC and all agree finally on what we need to do and then go forward from there?

**Comment by hoegrammer** [comment]
Yes let's set up IRC tomorrow. Aaron are you available tomorrow evening?

**Comment by AaronNGray** [comment]
Yeah I would like to do a Skype meeting first. I don't like Skype myself,
but would prefer to have face to face and am much nicer in person, than on
IM.

**Comment by AaronNGray** [comment]
I find it very hard to explain what I mean in text without it coming over
as brash and there are quite a lot of GP political issues we need to take
into account if we are going to go forward.

**Comment by hoegrammer** [comment]
OK I don't mind using Skype if there is a good enough internet connection

**Comment by hoegrammer** [comment]
Brashness isn't a problem for me though

**Comment by AaronNGray** [comment]
Yeah we will have a Skype session if you can get good internets :)

**Comment by Shakyamuni177te** [comment]
Sounds good to me.

On 26 July 2015 at 23:22, Aaron Gray notifications@github.com wrote:

> Yeah we will have a Skype session if you can get good internets :)
> 
> On 26 July 2015 at 20:34, Naomi notifications@github.com wrote:
> 
> > Brashness isn't a problem for me though
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/hoegrammer/democracy/issues/20#issuecomment-125031372>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hoegrammer/democracy/issues/20#issuecomment-125044682
> .

## 

https://github.com/Shakyamuni177te/The-Order-of-the-Mouse
