### ISSUE TITLE
Style the LoginStatus view

### ISSUE THREAD

**Issue by hoegrammer** [hoegrammer/democracy#23]
It works but it looks like a dog's dinner

**Comment by Shakyamuni177te** [comment]
Already working on it...

**Comment by Shakyamuni177te** [comment]
As we speak...

**Comment by Shakyamuni177te** [comment]
New styling tested on Firefox, Chrome and IE, across windows and linux. Reopen if you don't like the styling but I thought it looked pretty neat...

Now for the functionality (and getting the logged in user's name to display).
