### ISSUE TITLE
Logout button lacks functionality

### ISSUE THREAD

**Issue by Shakyamuni177te** [hoegrammer/democracy#25]
Need to return user to login page

**Comment by hoegrammer** [comment]
It does! (In Chrome anyway)

**Comment by hoegrammer** [comment]
It's just the test that is failing, which is because you changed the ID of the logout button and the test refers to it by id.

Please don't merge stuff to master with failing tests!

**Comment by Shakyamuni177te** [comment]
Oh, sorry. I didn't realise it changed the functionality.

**Comment by Shakyamuni177te** [comment]
All working fine now with all tests A-OK.
