### ISSUE TITLE
Voting view should be different from Proposal List view

### ISSUE THREAD

**Issue by hoegrammer** [hoegrammer/democracy#26]
It will be a very different view eventually with different actions etc. May as well make it separate now so that it's easier to combine the proposal list and form on the motions screen

**Comment by hoegrammer** [comment]
It will be a very different view eventually with different actions etc. May as well make it separate now so that it's easier to combine the proposal list and form on the motions screen

**Comment by Shakyamuni177te** [comment]
Do you have any particular rules you've formulated with regard to variable and function names? Might be useful to formulate naming conventions at this point?

**Comment by Shakyamuni177te** [comment]
Done, tested and pushed to repo.
