### ISSUE TITLE
Local Storage Object

### ISSUE THREAD

**Issue by Shakyamuni177te** [hoegrammer/democracy#28]
Any objections to implementing a HTML5 local storage object for temp storage of user data and motions data in the prototype while waiting on the backend?

**Comment by hoegrammer** [comment]
I don't see the need for it. Why would we need to refresh the page?

**Comment by Shakyamuni177te** [comment]
It would just be a placeholder until we can implement the backed, so we have data-storage for testing, but Aaron said he should have it basically ready soon, so probably just a distraction, you're right.

Also, we should probably add him to the repo?

**Comment by hoegrammer** [comment]
What I don't get is why we need data-storage for testing. Why would we need to refresh the page during a test?

**Comment by hoegrammer** [comment]
We should add him if he's going to do front-end work. The back-end should be a different repo

**Comment by Shakyamuni177te** [comment]
Yeah, it probably doesn't make sense. Was Aaron's suggestion. I'll just close the issue.

Aaron is definitely better for the backend than the frontend, I think, so we should probably leave that. He did show me some really useful code regarding centering and stuff, but the aesthetic was different than I would have gone with.
