### ISSUE TITLE
After clicking Add Proposal it gets a blue border

### ISSUE THREAD

**Issue by hoegrammer** [hoegrammer/democracy#9]
on chrome on linux anyway

**Comment by Shakyamuni177te** [comment]
This appears to be a browser specific issue that reproduces in some but not all browsers. Will look into further tomorrow.

**Comment by Shakyamuni177te** [comment]
Ok, I found the fix to the issue. Will create a pull request. Chrome specific effect requires browser hack to fix.

**Comment by Shakyamuni177te** [comment]
Tested and working on current build with FireFox 38.0 and Chrome Version 37.0.2062.120, running Ubuntu 12.04 (281580) (64-bit).

It appears we are blue-box free.
